repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.7.1'
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies: [types-decorator, types-PyYAML]