name: nerdd_module
channels:
- conda-forge
- defaults
dependencies:
- python=3.8.15
- rdkit=2022.09.1
# - xorg-libxrender=0.9.10
# - xorg-libxext=1.3.4
# - xorg-libxau=1.0.9
# - git=2.34.1
# - openssh=9.1p1