name: "Semantic release"

on:
  workflow_run:
    workflows: ["Test", "Check quality"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.repository == 'molinfo-vienna/nerdd-module' && github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    concurrency: release
      
    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.NERDD_APP_ID }}
        private-key: ${{ secrets.NERDD_APP_SECRET }}

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ steps.app-token.outputs.token }}

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@v9.11.0
      with:
        github_token: ${{ steps.app-token.outputs.token }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build
